from __future__ import annotations


APP_CONTENT = {
    "constraints": {
        "hidden_layers": {"min": 0, "max": 5},
        "neurons": {"min": 1, "max": 128},
    },
    "views": [
        {"id": "inicio", "label": "Inicio", "path": "/"},
        {"id": "construir-red", "label": "Construir red", "path": "/construir-red"},
        {"id": "explicacion", "label": "Explicacion", "path": "/explicacion"},
        {"id": "comparar-activaciones", "label": "Comparar activaciones", "path": "/comparar-activaciones"},
        {"id": "errores-comunes", "label": "Errores comunes", "path": "/errores-comunes"},
    ],
    "activation_catalog": [
        {
            "key": "linear",
            "label": "Lineal",
            "summary": "No curva: la salida crece al mismo ritmo que la entrada.",
            "best_for": "Salida de regresion y capas de lectura simples.",
            "watch_out": "Sin no linealidad, varias capas lineales se comportan como una sola.",
            "gradient": "Estable si el valor previo no explota.",
        },
        {
            "key": "sigmoid",
            "label": "Sigmoid",
            "summary": "Comprime todo entre 0 y 1.",
            "best_for": "Salida de clasificacion binaria y probabilidades.",
            "watch_out": "Se satura en valores muy altos o muy bajos y debilita el gradiente.",
            "gradient": "Debil en capas profundas.",
        },
        {
            "key": "tanh",
            "label": "Tanh",
            "summary": "Comprime entre -1 y 1 y centra mejor que sigmoid.",
            "best_for": "Capas ocultas pequenas cuando importa el signo.",
            "watch_out": "Tambien se satura si encadenas muchas capas.",
            "gradient": "Mejor que sigmoid cerca de cero; peor lejos del centro.",
        },
        {
            "key": "relu",
            "label": "ReLU",
            "summary": "Corta negativos y deja pasar positivos.",
            "best_for": "Capas ocultas profundas y entrenamiento eficiente.",
            "watch_out": "Si muchas neuronas quedan siempre en negativo, mueren.",
            "gradient": "Fuerte en positivos, bloqueado en negativos.",
        },
        {
            "key": "leaky_relu",
            "label": "Leaky ReLU",
            "summary": "Como ReLU, pero deja una fuga pequena en negativos.",
            "best_for": "Evitar neuronas muertas sin complicar el modelo.",
            "watch_out": "La pendiente negativa es pequena; no resuelve todo por si sola.",
            "gradient": "Mas robusto que ReLU en entradas negativas.",
        },
        {
            "key": "elu",
            "label": "ELU",
            "summary": "Mantiene positivos lineales y suaviza negativos.",
            "best_for": "Capas ocultas donde quieres activaciones mas suaves que ReLU.",
            "watch_out": "Mas costosa y aun puede saturar en negativos muy grandes.",
            "gradient": "Suele ser estable cerca del origen.",
        },
        {
            "key": "softplus",
            "label": "Softplus",
            "summary": "Version suave de ReLU, sin cortes bruscos.",
            "best_for": "Capas ocultas cuando quieres transiciones suaves.",
            "watch_out": "Puede aprender mas lento que ReLU por su suavidad.",
            "gradient": "Suave y casi siempre util, pero menos contundente.",
        },
        {
            "key": "gelu",
            "label": "GELU",
            "summary": "Pasa entradas segun su magnitud, de forma probabilistica y suave.",
            "best_for": "Modelos modernos donde importa estabilidad y expresividad.",
            "watch_out": "Mas compleja de explicar y de calcular que ReLU.",
            "gradient": "Buena estabilidad alrededor del centro.",
        },
        {
            "key": "swish",
            "label": "Swish",
            "summary": "Multiplica x por una sigmoid: deja pasar, pero con suavidad.",
            "best_for": "Capas ocultas que buscan una alternativa moderna a ReLU.",
            "watch_out": "Mas coste computacional y menos intuitiva para principiantes.",
            "gradient": "Suele mantener flujo util en un rango amplio.",
        },
    ],
    "output_activations": [
        {
            "key": "linear",
            "label": "Lineal",
            "summary": "Recomendada para salidas numericas sin cota.",
        },
        {
            "key": "sigmoid",
            "label": "Sigmoid",
            "summary": "Recomendada para probabilidad binaria entre 0 y 1.",
        },
        {
            "key": "softmax",
            "label": "Softmax",
            "summary": "Implementada para repartir probabilidad entre varias clases.",
        },
    ],
    "examples": [
        {
            "id": "celsius_fahrenheit",
            "title": "Regresion lineal simple: Celsius a Fahrenheit",
            "menu_label": "Celsius -> Fahrenheit",
            "task_type": "regression",
            "description": "Una entrada numerica produce una salida numerica. La relacion correcta es lineal.",
            "why_it_matters": "Es el ejemplo minimo para ver pesos, bias y perdida sin ruido innecesario.",
            "real_example": "Calibracion de sensores de temperatura.",
            "output_activation_recommendation": "Usa salida lineal porque la red debe producir cualquier numero real.",
            "loss_recommendation": "MSE (error cuadratico medio).",
            "default_output_activation": "linear",
            "supported_output_activations": ["linear", "sigmoid"],
            "output_size": 1,
            "input_features": [
                {
                    "key": "celsius",
                    "label": "Temperatura en Celsius",
                    "min": -20,
                    "max": 50,
                    "step": 0.5,
                    "default": 25,
                    "unit": "C",
                    "description": "Valor de entrada que la red debe transformar.",
                }
            ],
            "formula_hint": "F = C * 9 / 5 + 32",
            "expected_pattern": "La red debe aprender una recta: escalar y desplazar la entrada.",
            "minimal_config": "Funciona incluso con 0 capas ocultas y salida lineal, porque la tarea ya es lineal.",
            "recommended_config": {
                "hidden_layers": [],
                "output_activation": "linear",
                "note": "La arquitectura mas simple es tambien la mas correcta.",
            },
            "common_failures": [
                "Usar sigmoid en la salida comprime la respuesta y deja de servir para temperaturas altas.",
                "Anadir muchas capas no ayuda: solo complica una tarea que ya era una recta.",
            ],
        },
        {
            "id": "thermal_feel",
            "title": "Regresion no lineal: sensacion termica",
            "menu_label": "Sensacion termica",
            "task_type": "regression",
            "description": "La salida depende de varias entradas y de una combinacion no lineal entre ellas.",
            "why_it_matters": "Introduce interacciones entre variables y muestra por que una sola recta ya no basta.",
            "real_example": "Prediccion orientativa de confort en apps del tiempo.",
            "output_activation_recommendation": "Mantiene salida lineal, pero ya conviene al menos una capa oculta.",
            "loss_recommendation": "MSE o MAE, segun si penalizas mas errores grandes o medianos.",
            "default_output_activation": "linear",
            "supported_output_activations": ["linear"],
            "output_size": 1,
            "input_features": [
                {
                    "key": "temperature",
                    "label": "Temperatura",
                    "min": -10,
                    "max": 40,
                    "step": 0.5,
                    "default": 28,
                    "unit": "C",
                    "description": "Base termica real.",
                },
                {
                    "key": "humidity",
                    "label": "Humedad",
                    "min": 10,
                    "max": 100,
                    "step": 1,
                    "default": 70,
                    "unit": "%",
                    "description": "La humedad alta suele aumentar el bochorno.",
                },
                {
                    "key": "wind",
                    "label": "Viento",
                    "min": 0,
                    "max": 60,
                    "step": 1,
                    "default": 12,
                    "unit": "km/h",
                    "description": "El viento suele enfriar la sensacion.",
                },
            ],
            "formula_hint": "Sensacion = T + 0.03 * humedad - 0.18 * viento + curvatura por bochorno",
            "expected_pattern": "La red debe mezclar variables y captar que humedad y viento no pesan igual en todos los rangos.",
            "minimal_config": "Suele bastar 1 capa oculta de 6 a 12 neuronas con ReLU, Tanh o Swish.",
            "recommended_config": {
                "hidden_layers": [
                    {"neurons": 8, "activation": "relu"},
                ],
                "output_activation": "linear",
                "note": "Una sola capa oculta ya puede modelar curvatura razonable.",
            },
            "common_failures": [
                "Sin capa oculta, la red solo ajusta un plano y no capta el efecto no lineal de humedad alta.",
                "Con demasiadas sigmoid, el gradiente se apaga cuando humedad y viento llevan la suma a extremos.",
            ],
        },
        {
            "id": "spam_binary",
            "title": "Clasificacion binaria: spam o no spam",
            "menu_label": "Spam / no spam",
            "task_type": "binary",
            "description": "La salida es una probabilidad entre 0 y 1 para dos clases posibles.",
            "why_it_matters": "Muestra por que la salida debe leerse como probabilidad y por que la perdida cambia.",
            "real_example": "Filtrado preliminar de mensajes en un formulario.",
            "output_activation_recommendation": "Usa sigmoid en la salida para obtener una probabilidad interpretable.",
            "loss_recommendation": "Binary cross entropy.",
            "default_output_activation": "sigmoid",
            "supported_output_activations": ["sigmoid", "linear"],
            "output_size": 1,
            "input_features": [
                {
                    "key": "caps_ratio",
                    "label": "Porcentaje en mayusculas",
                    "min": 0,
                    "max": 100,
                    "step": 1,
                    "default": 35,
                    "unit": "%",
                    "description": "Mucho texto en mayusculas suele ser sospechoso.",
                },
                {
                    "key": "links",
                    "label": "Numero de enlaces",
                    "min": 0,
                    "max": 10,
                    "step": 1,
                    "default": 3,
                    "unit": "",
                    "description": "Muchos enlaces elevan el riesgo.",
                },
                {
                    "key": "urgency",
                    "label": "Tono urgente",
                    "min": 0,
                    "max": 10,
                    "step": 1,
                    "default": 7,
                    "unit": "/10",
                    "description": "Mas urgencia sintentica suele acercarse a spam.",
                },
            ],
            "formula_hint": "Spam = sigmoid(combinacion de mayusculas, enlaces y urgencia)",
            "expected_pattern": "La red debe separar mensajes normales de los mas sospechosos.",
            "minimal_config": "0 capas ocultas puede funcionar si la frontera es casi lineal; 1 capa pequena lo vuelve mas flexible.",
            "recommended_config": {
                "hidden_layers": [
                    {"neurons": 6, "activation": "tanh"},
                ],
                "output_activation": "sigmoid",
                "note": "Buena base para ver probabilidad sin volver el ejemplo opaco.",
            },
            "common_failures": [
                "Salida lineal deja una puntuacion sin cota y cuesta leerla como probabilidad.",
                "Una tasa de activaciones saturadas con sigmoid reduce la mejora del modelo.",
            ],
        },
        {
            "id": "flower_multiclass",
            "title": "Clasificacion multiclase: tipo de flor sintetica",
            "menu_label": "Flor simplificada",
            "task_type": "multiclass",
            "description": "La red reparte probabilidad entre tres clases: Lirio, Rosa y Margarita.",
            "why_it_matters": "Permite explicar por que Softmax compara clases entre si, no una por separado.",
            "real_example": "Clasificacion basica de categorias visuales o de producto.",
            "output_activation_recommendation": "Usa softmax para que las tres probabilidades sumen 1.",
            "loss_recommendation": "Categorical cross entropy.",
            "default_output_activation": "softmax",
            "supported_output_activations": ["softmax", "linear"],
            "output_size": 3,
            "classes": ["Lirio", "Rosa", "Margarita"],
            "input_features": [
                {
                    "key": "petal_length",
                    "label": "Largo del petalo",
                    "min": 1,
                    "max": 8,
                    "step": 0.1,
                    "default": 5.4,
                    "unit": "cm",
                    "description": "Rasgo continuo sencillo.",
                },
                {
                    "key": "petal_width",
                    "label": "Ancho del petalo",
                    "min": 0.1,
                    "max": 3.5,
                    "step": 0.1,
                    "default": 1.7,
                    "unit": "cm",
                    "description": "Segundo rasgo continuo para separar clases.",
                },
                {
                    "key": "fragrance",
                    "label": "Intensidad de aroma",
                    "min": 0,
                    "max": 10,
                    "step": 0.5,
                    "default": 4,
                    "unit": "/10",
                    "description": "Variable sintetica para que no todo dependa solo del tamano.",
                },
            ],
            "formula_hint": "Cada clase recibe un score y softmax los convierte en probabilidades comparables.",
            "expected_pattern": "La red debe crear fronteras entre tres regiones, no solo un si/no.",
            "minimal_config": "1 capa oculta de 8 a 12 neuronas suele bastar para una frontera multiclase sencilla.",
            "recommended_config": {
                "hidden_layers": [
                    {"neurons": 10, "activation": "relu"},
                ],
                "output_activation": "softmax",
                "note": "Softmax esta implementada para visualizar probabilidades de tres clases.",
            },
            "common_failures": [
                "Usar sigmoid por clase deja probabilidades no normalizadas y complica la lectura del resultado.",
                "Sin capa oculta, la frontera puede quedarse demasiado rigida.",
            ],
        },
        {
            "id": "xor_gate",
            "title": "XOR: por que una sola capa no basta",
            "menu_label": "XOR",
            "task_type": "binary",
            "description": "La salida vale 1 solo cuando las entradas son distintas.",
            "why_it_matters": "Es el ejemplo clasico que demuestra el limite de una sola capa lineal.",
            "real_example": "Combinacion de reglas donde una sola frontera recta no puede separar el patron.",
            "output_activation_recommendation": "La salida suele ser sigmoid, pero necesitas al menos una capa oculta.",
            "loss_recommendation": "Binary cross entropy.",
            "default_output_activation": "sigmoid",
            "supported_output_activations": ["sigmoid", "linear"],
            "output_size": 1,
            "input_features": [
                {
                    "key": "x1",
                    "label": "Entrada x1",
                    "min": 0,
                    "max": 1,
                    "step": 1,
                    "default": 1,
                    "unit": "",
                    "description": "Primer bit.",
                },
                {
                    "key": "x2",
                    "label": "Entrada x2",
                    "min": 0,
                    "max": 1,
                    "step": 1,
                    "default": 0,
                    "unit": "",
                    "description": "Segundo bit.",
                },
            ],
            "formula_hint": "XOR = 1 cuando x1 != x2",
            "expected_pattern": "La red debe combinar dos regiones separadas. Una sola recta no puede hacerlo.",
            "minimal_config": "Necesitas al menos 1 capa oculta con 2 neuronas y activacion no lineal.",
            "recommended_config": {
                "hidden_layers": [
                    {"neurons": 2, "activation": "tanh"},
                ],
                "output_activation": "sigmoid",
                "note": "Es el tamano minimo didactico para mostrar separacion no lineal.",
            },
            "common_failures": [
                "Con 0 capas ocultas, la salida no puede separar los dos casos positivos a la vez.",
                "ReLU con pesos mal alineados puede dejar una neurona sin contribuir y volver a fallar.",
            ],
        },
    ],
    "gradient_scenarios": [
        {
            "id": "sigmoid_deep",
            "label": "Sigmoid en 5 capas",
            "summary": "El gradiente se debilita porque cada capa multiplica una derivada menor que 1.",
            "apply": {
                "example_id": "spam_binary",
                "hidden_layers": [
                    {"neurons": 32, "activation": "sigmoid"},
                    {"neurons": 32, "activation": "sigmoid"},
                    {"neurons": 24, "activation": "sigmoid"},
                    {"neurons": 16, "activation": "sigmoid"},
                    {"neurons": 8, "activation": "sigmoid"},
                ],
                "output_activation": "sigmoid",
            },
        },
        {
            "id": "relu_dead",
            "label": "ReLU con neuronas muertas",
            "summary": "Si muchas preactivaciones son negativas, varias neuronas se quedan en cero y dejan de aprender.",
            "apply": {
                "example_id": "thermal_feel",
                "hidden_layers": [
                    {"neurons": 12, "activation": "relu"},
                    {"neurons": 12, "activation": "relu"},
                    {"neurons": 8, "activation": "relu"},
                ],
                "output_activation": "linear",
                "input_overrides": {
                    "temperature": -8,
                    "humidity": 20,
                    "wind": 35,
                },
            },
        },
        {
            "id": "healthy_baseline",
            "label": "Base razonable",
            "summary": "Una capa oculta pequena con activacion adecuada suele mantener un flujo sano.",
            "apply": {
                "example_id": "thermal_feel",
                "hidden_layers": [
                    {"neurons": 8, "activation": "leaky_relu"},
                ],
                "output_activation": "linear",
            },
        },
    ],
    "common_errors": [
        {
            "title": "La perdida no baja",
            "symptom": "El modelo repite casi la misma salida y el error apenas cambia.",
            "detect": "En esta app se ve como salida plana y gradiente debil o bloqueado en varias capas.",
            "fix": "Reduce profundidad innecesaria, cambia sigmoid por ReLU/Leaky ReLU o simplifica la tarea.",
        },
        {
            "title": "Salida mal elegida",
            "symptom": "La red da numeros raros o probabilidades poco interpretables.",
            "detect": "Regresion con sigmoid queda recortada; clasificacion con salida lineal no se lee como probabilidad.",
            "fix": "Usa lineal para regresion, sigmoid para binaria y softmax para multiclase.",
        },
        {
            "title": "Saturacion",
            "symptom": "Muchas activaciones quedan pegadas a 0, 1 o -1.",
            "detect": "El panel de gradiente pasa a debil aunque haya varias capas activas.",
            "fix": "Normaliza entradas, usa menos profundidad o cambia a activaciones menos saturables.",
        },
        {
            "title": "Neuronas muertas",
            "symptom": "Varias ReLU producen cero todo el tiempo.",
            "detect": "La capa marca gradiente bloqueado y muestra alto porcentaje de activaciones en cero.",
            "fix": "Prueba Leaky ReLU, ELU o ajusta entradas y sesgos para no dejar todo en negativo.",
        },
    ],
    "implementation_phases": [
        {
            "phase": "Fase 1 - MVP",
            "scope": "Navegacion base, 3 ejemplos clave, constructor simple, 5 activaciones y semaforo de gradiente.",
        },
        {
            "phase": "Fase 2 - Completa",
            "scope": "Activaciones avanzadas, comparador ampliado, ejemplos no lineales y multiclase con softmax.",
        },
        {
            "phase": "Fase 3 - Refinado",
            "scope": "Mas escenarios guiados, mejoras visuales y ejercicios con autoevaluacion.",
        },
    ],
    "proposed_structure": [
        "Entendiendo_una_Red_Neuronal.py",
        "app/educational_content.py",
        "assets/css/base.css",
        "assets/css/main.css",
        "assets/js/learning_app.js",
        "templates/main.html",
        "templates/partials/header.html",
        "docs/00_introduccion.md",
        "docs/01_neurona_y_capas.md",
        "docs/02_forward_pass.md",
        "docs/03_activaciones.md",
        "docs/04_perdida_y_optimizacion.md",
        "docs/05_backprop_gradiente.md",
        "docs/06_como_elegir_arquitectura.md",
        "docs/07_casos_practicos.md",
        "docs/glosario.md",
    ],
    "wireframes": [
        "Inicio: barra superior, selector de ejemplo, tarjetas con objetivo, arquitectura minima y practica sugerida.",
        "Construir red: panel izquierdo con capas y activaciones; panel derecho con forward, salida y gradiente por capa.",
        "Explicacion: acordeones breves para conceptos base y razon del ejemplo elegido.",
        "Comparar activaciones: tabla simple con que hace, cuando usar y fallo tipico.",
        "Errores comunes: tarjetas de sintoma, como detectarlo y correccion recomendada.",
    ],
    "microcopy": {
        "hero": "Aprende que hace una red neuronal sin ocultar el mecanismo.",
        "builder_hint": "Ajusta pocas cosas cada vez: profundidad, tamano y activacion. Luego compara el efecto.",
        "gradient_hint": "Fuerte = la correccion aun llega. Debil = aprende lento. Bloqueado = casi no corrige.",
        "activation_hint": "No hay activacion universal: la salida depende del tipo de problema.",
        "errors_hint": "Si la red falla, primero revisa la salida y la activacion antes de anadir mas capas.",
    },
}


def get_app_content() -> dict:
    return APP_CONTENT
